apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-experiment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: flask-experiment
  template:
    metadata:
      labels:
        app: flask-experiment
    spec:
      containers:
      - image: docker.io/faderosyad/flask-experiment:latest
        name: flask-experiment
        ports:
        - containerPort: 80
        resource:
          limits:
            cpu = "0.5"
            memory = "512Mi"
          request:
            cpu = "250m"
            memory = "50Mi"