apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-project
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: flask-project
  template:
    metadata:
      labels:
        app: flask-project
    spec:
      containers:
      - image: docker.io/faderosyad/flask-experiment:latest
        name: flask-project
        ports:
        - containerPort: 80