apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: discord-notification
        image: alpine:latest
        command: ["/bin/sh","-c"]
        args: ["apk add curl; curl -H \"Content-Type: application/json\" -X POST -d '{\"content\":\"Deployment Success <@!534115621130993665>\"}' https://discord.com/api/webhooks/803780068546969600/p87B6fMQoCplQZODuc14nUgPYyFBL8jEyur8NObmyLXFPhSsB2h0jrp0gsM9sJqYUP3t; sleep 20]
      restartPolicy: Never
  backoffLimit: 0